/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    EpAd: typeof import('~icons/ep/ad')['default']
    EpDelete: typeof import('~icons/ep/delete')['default']
    EpPlus: typeof import('~icons/ep/plus')['default']
    EpSearch: typeof import('~icons/ep/search')['default']
    EpSuccessFilled: typeof import('~icons/ep/success-filled')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IEpCircleCheck: typeof import('~icons/ep/circle-check')['default']
    IEpCircleCheckFilled: typeof import('~icons/ep/circle-check-filled')['default']
    IEpSearch: typeof import('~icons/ep/search')['default']
    RawData: typeof import('./src/components/RawData.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
