version: 2
jobs:
  build:
    docker:
      - image: cimg/node:22.5.1
    branches:
      only:
        - main
    steps:
      - add_ssh_keys:
          fingerprints:
            - ${SSH_KEYS}
      - checkout
      # 使用node_modules缓存
      - restore_cache:
          keys:
            - node_dependencies
      - run:
          name: Clean Npm Cache
          command: npm cache clean --force
      - run:
          name: Install
          command: npm install
      # 对node_modules 进行缓存
      - save_cache:
          paths:
            - node_modules
          key: node_dependencies
      - run:
          name: Build
          command: npm run build
      - run:
          name: Auth Deploy
          # 设置文件权限
          command: chmod +x scripts/deploy.sh
      - run:
          name: Deploy
          # 执行shell脚本
          command: ./scripts/deploy.sh
